$(function(){
	$(".header-tou").tap(function(){
		$(".zhxx-djh").toggleClass("zhxx-togg");
		$(".zhxx-djnr").toggleClass("zhxx-togg");
	});
	$(".zhxx-djh").tap(function(){
		$(".zhxx-djh").toggleClass("zhxx-togg");
		$(".zhxx-djnr").toggleClass("zhxx-togg");
	});
});
